# Generated by Django 6.1.2 on 2026-10-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='foto',
            field=models.FileField(blank=True, null=True, upload_to='produtos/'),
        ),
    ]
